name: WoW auctions
on:
  push:
    branches:
      - master
    

env:
  BASIC_AUTH: ${{ secrets.BASIC_AUTH }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_ACCEESS_KEY_SECRET: ${{ secrets.AWS_ACCEESS_KE_SECRET }}

jobs:
  download_auctions:
    name: 'Auction report pipeline'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'Install dependencies'
        run: pip install -r requirements.txt
      - name: 'Download auctions'
        run: python -u wowapi.py