name: Mythic leaderboard
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 20 * * 2"
    

env:
  BASIC_AUTH: ${{ secrets.BASIC_AUTH }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_ACCEESS_KEY_SECRET: ${{ secrets.AWS_ACCEESS_KE_SECRET }}
  MONGO_PWD: ${{ secrets.MONGO_PWD }}
  MONGO_USER: ${{ secrets.MONGO_USER }}

jobs:
  leaderboard_crawler:
    name: mythic-leaderboard
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: pip install -r mythics/requirements.txt
      - name: Run mythics leaderboard
        run: python mythics/crawler.py